### ISSUE TITLE
[QUESTION]: Colored output for DEBUG level

### ISSUE THREAD

**Issue by ghost** [bschiffthaler/BSlogger#2]
Hi @bschiffthaler,

Greetings.

Thanks for this wonderful tool for logging c++ applications. I was wondering if the DEBUG level has no colored output since in my project the DEBUG level is colored in white.

![Screenshot from 2022-05-20 15-45-48](https://user-images.githubusercontent.com/35694200/169608194-9209d535-6964-4e57-89ab-3b0952730aa1.png)

**Comment by bschiffthaler** [comment]
Hi. This is intended. If you want to override the colors, edit the header definitions [here](https://github.com/bschiffthaler/BSlogger/blob/master/src/BSlogger.hpp#L40). Here is some info on ANSI escape codes to define colors: https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by ghost** [comment]
Thanks @bschiffthaler I will look into this feature.
